name: ArduinoBuild

env:
  SKETCH_NAME: ICSMeter
  BUILD_DIR: /home/runner/ICSMeter/build
  GHPAGE_DIR: /home/runner/ICSMeter/gh-pages
  ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL: true
  PLATFORM_URL: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json

on:
  push: # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    branches-ignore: [ghpages]
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.hpp'
    - '**.h'
    - '**.c'
    - '**ArduinoBuild.yml'
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: ${{matrix.board}}@${{matrix.platform-version}}

    runs-on: ubuntu-latest

    strategy:
      matrix:

        platform-url:
          - https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json

        include:
          - board: m5stack-core2
            platform: esp32
            archi: esp32
            platform-version: 2.0.3

      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Create build folder
        run: |
          mkdir -p ${{ env.BUILD_DIR }}
          mkdir -p ${{ env.GHPAGE_DIR }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Install lib deps and build
        env:
          dstname: ${{ env.SKETCH_NAME }}.${{matrix.board}}.bin
        run: |
          mkdir ~/.arduino15
          arduino-cli core update-index --additional-urls ${{ env.PLATFORM_URL }}
          arduino-cli core install esp32:esp32 --additional-urls ${{ env.PLATFORM_URL }}
          arduino-cli lib install --no-deps M5Stack-SD-Updater
          arduino-cli lib install --no-deps ESP32-targz
          arduino-cli lib install --no-deps M5Unified
          arduino-cli lib install --no-deps M5GFX
          arduino-cli lib install --no-deps LGFXMeter
          arduino-cli lib install --no-deps FastLED
          arduino-cli lib install --git-url https://github.com/me-no-dev/ESPAsyncWebServer.git
          arduino-cli lib install --git-url https://github.com/me-no-dev/AsyncTCP.git
          arduino-cli compile --verbose --warnings all --fqbn esp32:esp32:m5stack-core2 --build-path ${{ env.BUILD_DIR }} ${{ env.SKETCH_NAME }}.ino

      - name: Prepare gh-pages
        env:
          srcname: ${{ env.BUILD_DIR }}/${{ env.SKETCH_NAME }}.ino.bin
        run: |
          cp ${{ env.BUILD_DIR }}/${{ env.srcname }} ${{ env.GHPAGE_DIR }}/${{ env.dstname }}
          echo "<!doctype html><html><meta charset=utf8><body>Last update: " > ${{ env.GHPAGE_DIR }}/index.html
          echo ${{ steps.date.outputs.date }} >> ${{ env.GHPAGE_DIR }}/index.html
          echo "<br>" >> ${{ env.GHPAGE_DIR }}/index.html
          echo "<a href=${{ env.dstname }}>${{ env.dstname }}</a></body></html>" >> ${{ env.GHPAGE_DIR }}/index.html
          echo '{"last_update":"${{ steps.date.outputs.date }}","board":"${{matrix.board}}","firmware":"${{ env.dstname }}"}' > ${{ env.GHPAGE_DIR }}/index.json


# https://tobozo.github.io/ICSMeter/ICSMeter.m5stack-core2.bin

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: "Arduino Build"
          path: ${{ env.BUILD_DIR }}/ICSMeter.ino.bin

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ${{ env.GHPAGE_DIR }}/ # The folder the action should deploy.
#          token: ${{ secrets.GH_TOKEN }}


