name: ArduinoBuild

env:
  SKETCH_NAME: ICSMeter
  BUILD_DIR: /home/runner/ICSMeter/build
  ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL: true
  PLATFORM_URL: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json

on:
  push: # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.hpp'
    - '**.h'
    - '**.c'
    - '**ArduinoBuild.yml'
  pull_request:

jobs:
  build:
    name: ${{matrix.board}}@${{matrix.platform-version}}

    runs-on: ubuntu-latest

    strategy:
      matrix:

        platform-url:
          - https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json

        include:
          - board: m5stack-core2
            platform: esp32
            archi: esp32
            platform-version: 2.0.3

      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Create build folder
        run: mkdir -p ${{ env.BUILD_DIR }}

      - name: Install lib deps
        run: |
          arduino-cli lib install --no-deps M5Stack-SD-Updater
          arduino-cli lib install --no-deps ESP32-targz
          arduino-cli lib install --no-deps M5Unified
          arduino-cli lib install --no-deps M5GFX
          arduino-cli lib install --no-deps LGFXMeter
          arduino-cli lib install --no-deps FastLED
          arduino-cli lib install --git-url https://github.com/me-no-dev/ESPAsyncWebServer.git
          arduino-cli lib install --git-url https://github.com/me-no-dev/AsyncTCP.git
          arduino-cli core install esp32:esp32
          arduino-cli compile --verbose --warnings all --fqbn esp32:esp32:m5stack-core2 --additional-urls ${{ env.PLATFORM_URL }} --build-path ${{ env.BUILD_DIR }} ICSMeter.ino

      #- name: Compile Sketch
        #uses: ArminJo/arduino-test-compile@v3
        #with:
          #arduino-board-fqbn: ${{matrix.platform}}:${{matrix.archi}}:${{matrix.board}}
          #arduino-platform: ${{matrix.platform}}:${{matrix.archi}}@${{matrix.platform-version}}
          #platform-url: ${{ matrix.platform-url }}
          #sketch-names: ${{ env.SKETCH_NAME }}.ino
          #set-build-path: true

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: "Arduino Build"
          path: ${{ env.BUILD_DIR }}/ICSMeter.ino.bin


